from fpdf import FPDF
from datetime import datetime, timezone

from src.data.ui_constants import LOGO_PATH_LIGHT
from src.util.formatting import currency_symbol


def generate_portfolio_pdf(df, filename, title, kas_amount, current_price_usd,
                           circ_supply_b, currency, btc_market_cap, progress_cb=None):
    formatted_title = (title.capitalize() + " Portfolio Projection") if title else "Unnamed Portfolio Projection"
    from src.data.constants import EXCHANGE_RATES
    rate = EXCHANGE_RATES.get(currency.upper(), 1.0)
    sym = currency_symbol(currency)

    circ_supply = circ_supply_b * 1_000_000_000
    market_cap = current_price_usd * circ_supply * rate
    portfolio_value = kas_amount * current_price_usd * rate

    price_needed_for_1m_usd = 1_000_000 / kas_amount if kas_amount > 0 else 0
    mcap_needed_for_1m_usd = price_needed_for_1m_usd * circ_supply
    mcap_needed_for_1m = mcap_needed_for_1m_usd * rate
    btc_mcap_cur = (btc_market_cap or 0) * rate
    ratio = (mcap_needed_for_1m_usd / btc_market_cap) if btc_market_cap else 0

    pdf = FPDF()
    pdf.set_auto_page_break(auto=False, margin=12)
    pdf.add_page()
    try: pdf.image(LOGO_PATH_LIGHT, x=10, y=6, w=50)
    except Exception: pass

    pdf.set_font("Helvetica", "B", 22)
    title_w = pdf.get_string_width(formatted_title)
    pdf.set_xy(200 - title_w - 10, 10); pdf.cell(0, 10, formatted_title, ln=True, align="R")

    pdf.set_font("Helvetica", "", 7)
    sub = "Generated by Kaspa Portfolio Projector (KPP)"
    sub_w = pdf.get_string_width(sub)
    pdf.set_xy(200 - sub_w - 10, 20); pdf.cell(0, 5, sub, ln=True, align="R")

    date = datetime.now(timezone.utc).strftime("%B %d, %Y")
    date_w = pdf.get_string_width(date)
    pdf.set_xy(200 - date_w - 10, 25); pdf.cell(0, 5, date, ln=True, align="R")

    pdf.set_draw_color(150, 150, 150); pdf.line(10, 30, 200, 30); pdf.ln(10)

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 14); pdf.cell(0, 8, "Portfolio Facts", ln=True); pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)

    def mm(v): return f"{sym}{v:,.2f}"
    summary = (
        f"The {title or 'Unnamed'} Kaspa portfolio holds {kas_amount:,.2f} KAS. "
        f"Current portfolio value: {mm(portfolio_value)}. "
        f"Kaspa market cap: {mm(market_cap)}. "
        f"To reach a $1M portfolio: KAS price {mm(price_needed_for_1m_usd*rate)} "
        f"and market cap {mm(mcap_needed_for_1m)} "
        f"(~{ratio:.2f} × current Bitcoin market cap of {mm(btc_mcap_cur)})."
    )
    pdf.multi_cell(0, 5, summary); pdf.ln(4)

    fields = [
        ("Current KAS Price:", f"{sym}{(current_price_usd*rate):,.4f}"),
        ("Current KAS Holdings:", f"{kas_amount:,.2f} KAS"),
        ("Current KAS Portfolio Value:", mm(portfolio_value)),
        ("Current KAS Market Cap:", mm(market_cap)),
        ("KAS Price Needed for $1M Portfolio:", mm(price_needed_for_1m_usd*rate)),
        ("KAS Market Cap Needed for $1M Portfolio:", mm(mcap_needed_for_1m)),
    ]
    pdf.set_font("Helvetica", "", 11)
    for k, v in fields:
        pdf.cell(90, 6, k, ln=False)
        pdf.cell(0, 6, v, ln=True, align="R")
    pdf.ln(6)

    header_bg = (230, 230, 230)
    row_fill_a = (248, 248, 248)
    row_fill_b = (255, 255, 255)
    text_norm = (20, 20, 20)
    red = (200, 0, 0); green = (0, 140, 70); black = text_norm

    def table_header():
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_fill_color(*header_bg); pdf.set_text_color(*text_norm)
        pdf.cell(63, 8, f"Price ({currency.upper()})", border=1, align="C", fill=True)
        pdf.cell(63, 8, f"Portfolio ({currency.upper()})", border=1, align="C", fill=True)
        pdf.cell(63, 8, f"Market Cap ({currency.upper()})", border=1, align="C", fill=True)
        pdf.ln()
        pdf.set_font("Helvetica", "", 10)

    def page_break_if_needed():
        if pdf.get_y() > 265:
            pdf.add_page(); table_header()

    table_header()
    total = len(df)
    for i, (_, row) in enumerate(df.iterrows(), 1):
        page_break_if_needed()
        fill_color = row_fill_a if i % 2 == 0 else row_fill_b
        pdf.set_fill_color(*fill_color)
        color = red if row["Color"] == "red" else green if row["Color"] == "green" else black
        pdf.set_text_color(*color)
        pdf.cell(63, 8, f"{sym}{row['Price']:,.2f}", border=1, align="C", fill=True)
        pdf.set_text_color(*text_norm)
        pdf.cell(63, 8, f"{sym}{row['Portfolio']:,.2f}", border=1, align="C", fill=True)
        pdf.cell(63, 8, f"{sym}{row['Market Cap']:,.2f}", border=1, align="C", fill=True)
        pdf.ln()
        if progress_cb and total:
            progress_cb(i * 100.0 / total)

    pdf.set_y(-10); pdf.set_text_color(0, 0, 0); pdf.set_font("Helvetica", "", 7)
    pdf.cell(0, 5, "Generated by Kaspa Portfolio Projector (KPP)", 0, 0, "C")
    pdf.output(filename)


